steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
    secretEnv: ['USERNAME', 'PASSWORD']

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build -t $$USERNAME/musetalk:latest .']
    secretEnv: ['USERNAME']

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker push $$USERNAME/musetalk:latest']
    secretEnv: ['USERNAME']

availableSecrets:
  secretManager:
  - versionName: projects/1089598673424/secrets/docker-password/versions/1
    env: 'PASSWORD'
  - versionName: projects/1089598673424/secrets/docker-username/versions/1
    env: 'USERNAME'
